# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: ankit-rathi.github.io
description: An alternate to ankitrathi.com
github_username: ankit-rathi

favicon: images/favicon.ico

include:
  - _pages

header_pages:
 - _pages/blog.md
 
# See https://jekyllrb.com/docs/pagination/
# For pagination to work, you cannot have index.md at the root of your repo, instead you must rename this file to index.html
paginate: 5
paginate_path: /page:num/

theme: minima
